service: task-manager-${opt:stage, self:provider.stage}

custom:
  settings:
    USERS_TABLE: task-manager-users-${opt:stage, self:provider.stage}
    TASKS_TABLE: task-manager-tasks-${opt:stage, self:provider.stage}

package:
  individually: true
  excludeDevDependencies: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
  environment:
    SECRET_KEY: ${file(serverless.${opt:stage, self:provider.stage}.yaml):secretKey}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - dynamodb:*
      Resource:
        - 'arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.settings.USERS_TABLE}'
        - 'arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.settings.TASKS_TABLE}'

functions:
  auth:
    handler: dist/auth.authenticate
  login:
    handler: dist/auth.login
    events:
      - http:
          path: /api/auth/login
          method: post
          cors: true
  getUsers:
    handler: dist/users.getUsers
    events:
      - http:
          path: /api/users
          method: get
          cors: true
          authorizer: auth
  createUser:
    handler: dist/users.createUser
    events:
      - http:
          path: /api/users
          method: post
          cors: true
  deleteUser:
    handler: dist/users.deleteUser
    events:
      - http:
          path: /api/users/{id}
          method: delete
          cors: true
          authorizer: auth
  getTasks:
    handler: dist/tasks.getTasks
    events:
      - http:
          path: /api/tasks
          method: get
          cors: true
          authorizer: auth
  createTask:
    handler: dist/tasks.createTask
    events:
      - http:
          path: /api/tasks
          method: post
          cors: true
          authorizer: auth
  deleteTask:
    handler: dist/tasks.deleteTask
    events:
      - http:
          path: /api/tasks/{id}
          method: delete
          cors: true
          authorizer: auth
  createComment:
    handler: dist/comments.createComment
    events:
      - http:
          path: /api/comments/{taskId}
          method: post
          cors: true
          authorizer: auth

resources:
  - ${file(templates/dynamo.yml)}
  - ${file(templates/api-gateway.yml)}
